social_network/social_network/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls', 'webapp')),
    path('auth/', include('django.contrib.auth.urls'))
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_network/webapp/urls.py
from django.urls import path
from webapp.views import PostListView, PostDetailView, PostCreateView, PostUpdateView, delete_post,\
                        UserListView, UserDetailView, UserUpdateView


app_name = 'webapp'

urlpatterns = [
    path('', PostListView.as_view(), name='post_list'),
    path('post/create', PostCreateView.as_view(), name='post_create'),
    path('post/<int:pk>', PostDetailView.as_view(), name = 'post_detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post_update'),
    path('post/<int:post_id>/delete', delete_post, name='post_delete'),

    path('user', UserListView.as_view(), name='user_list'),
    path('user/<int:pk>', UserDetailView.as_view(), name='user_detail'),
    path('user/<int:pk>/update', UserUpdateView.as_view(), name='user_update')
]

social_network/webapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Userinfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.PROTECT, related_name='client', verbose_name='Пользователь')
    phone = models.CharField(max_length=50, verbose_name='Телефон')
    photo = models.ImageField(null=True, blank=True, verbose_name='Фотография')
    friends = models.ManyToManyField(User, related_name='clients_friend', verbose_name='друзья')



class Post(models.Model):
    title = models.CharField(max_length=200, null=False, blank=False, verbose_name='Заголовок')
    text = models.TextField(max_length=3000, null=False, blank=False, verbose_name='Текст')
    author = models.ForeignKey(User, null=False, blank=False, related_name='post_author', on_delete=models.PROTECT, verbose_name='Автор')
    created_at = models.DateField(verbose_name='Время создания')

    def __str__(self):
        return self.title

social_network/webapp/views.py
from django.shortcuts import reverse,redirect, get_object_or_404, Http404
from django.views.generic import DetailView, CreateView, UpdateView, ListView
from webapp.models import Userinfo, Post
from django.urls import reverse_lazy
from webapp.form import PostForm, UserForm
from django.contrib.auth.mixins import LoginRequiredMixin


class PostListView(ListView):
    model = Post
    template_name = 'post_list.html'

    def get_queryset(self):
        return self.model.objects.order_by('-created_at')


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = 'post_create.html'
    form_class = PostForm

    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.object.pk})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = 'post_update.html'
    form_class = PostForm


    def get_object(self, queryset = Post.objects.all()):
        object = super(PostUpdateView, self).get_object()

        if object.author == self.request.user:
            return object

        else:
            raise Http404()


    def get_success_url(self):
        return reverse('webapp:post_detail', kwargs={'pk': self.object.pk})


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author == request.user:
        post.delete()
        return redirect('webapp:post_list')
    else:
        return redirect('webapp:post_detail', post_id)


class UserListView(ListView):
    model = Userinfo
    template_name = 'user_list.html'


class UserDetailView(DetailView):
    model = Userinfo
    template_name = 'user_detail.html'


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = Userinfo
    template_name = 'user_update.html'
    form_class = UserForm

    def get_object(self, queryset = Userinfo.objects.all()):
        object = super(UserUpdateView, self).get_object()

        if object.user == self.request.user:
            return object

        else:
            raise Http404()

    def get_success_url(self):
        return reverse('webapp:user_detail', kwargs={'pk': self.object.pk})

social_network/webapp/templates/base.html
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    {% block styles %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light sticky-top">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav container">

                  <li class="nav-item"><a class="nav-link" href="{% url 'webapp:post_list' %}">Новости</a></li>
                  <li class="nav-item"><a class="nav-link" href="{% url 'webapp:user_list' %}">Пользователи</a></li>

                    {% if user.is_authenticated %}
                        <li class="nav-item navbar-text">Привет, {{ user.username }}!</li>
                        <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link">Выход</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:user_detail' request.user.client.pk %}">Личный кабинет</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'webapp:post_create' %}">Добавить новость</a></li>
                    {% else %}
                        <li class="nav-item"><a href="{% url 'login' %}" class="nav-link">Вход</a></li>
                    {% endif %}

            {% block menu %}{% endblock %}
        </ul>
    </div>
</nav>
<div class="container">
    {% block content %}{% endblock %}
</div>
<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
{% block scripts %}{% endblock %}
</body>
</html>

social_network/webapp/templates/fill_form.html
<div class="form-group row">
    {% csrf_token %}
    <label class="col-sm-2 col-form-label">Заголовок:</label>
    <div class="col-sm-4">
          {{ form.title }}
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label">Текст:</label>
    <div class="col-sm-4">
        {{ form.text }}
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label">Дата:</label>
    <div class="col-sm-4">
        {{ form.created_at }}
    </div>
</div>
<div class="form-group row">
<label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4  mt-2">
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
</div>

social_network/webapp/templates/post_create.html
{% extends 'base.html' %}
{% block title %}Статьи{% endblock %}
{% block content %}
    <h1>Новый пост</h1>
    <form action="{% url 'webapp:post_create' %}" method="post" enctype="multipart/form-data">
        {% include 'fill_form.html' %}
    </form>

{% endblock %}

social_network/webapp/templates/post_detail.html
{% extends 'base.html' %}
{% block title %}Новость{% endblock %}
{% block content %}


    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ post.title }}</h5>
        <p class="card-text">{{ post.text }}</p>
        <p class="card-text">{{ post.created_at }}</p>

        {% if request.user == post.author %}
            <button type="button" class="btn btn-dark float-right" data-toggle="modal" data-placement="top" title="Удалить" data-target="#Modal_{{ post.pk }}">Удалить</button>
            <a href="{% url 'webapp:post_update' post.pk %}" class="btn btn-primary float-right mr-2">Редактировать</a>
        {% endif %}
      </div>
    </div>

    <div class="modal fade" id="Modal_{{ post.pk }}" tabindex="-1" role="dialog" aria-labelledby="Modal_{{ post.pk }}Label" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content text-center">
            <div class="modal-header">
              <h3 class="modal-title" id="Modal_{{ record.pk }}Label">Вы уверены?</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <a class="btn btn-primary modal_btn" href="{% url 'webapp:post_delete' post.pk %}">Да</a>
                <a class="btn btn-secondary modal_btn" href="{% url 'webapp:post_detail' post.pk %}">Нет</a>
              </div>
          </div>
        </div>
    </div>
{% endblock %}

social_network/webapp/templates/post_list.html
{% extends 'base.html' %}
{% block title %}Новости{% endblock %}
{% block content %}
        <div class="card-group">
            {% for post in post_list %}
                <div class="card">
                    <div class="card-body">
                    <a href="{% url 'webapp:post_detail' post.pk %}"><h5 class="card-title">{{ post.title }}</h5></a>
                    <p class="card-text">{{ post.author }}</p>
                    <p class="card-text">{{ post.created_at }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
{% endblock %}

social_network/webapp/templates/post_update.html
{% extends 'base.html' %}
{% block title %}Изменить{% endblock %}
{% block content %}
    <h1>Редактирование</h1>
    <form action="{% url 'webapp:post_update' form.instance.pk %}" method="post" enctype="multipart/form-data">
        {% include 'fill_form.html' %}
    </form>
{% endblock %}

social_network/webapp/templates/user_detail.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
    <div class="card border">
        <div class="card-header">
            {% if request.user == userinfo.user %}
            <h2>Личный кабинет</h2>
            {% else %}
            <h2>Страница пользователя</h2>
            {% endif %}
            Имя: {{ userinfo.user }}
        </div>
        <div class="card-body">
             {% if userinfo.photo %}
            <span class="card-img"><img src="{{ userinfo.photo.url }}" alt="Card image cap"></span>
              {% endif %}
            <p class="card-text" id="phone"> Телефон<input id="add-item-btn" type="button" value="Показать телефон"></p>




            <p class="card-text"> Почта: {{ userinfo.email }}</p>
            <p class="card-text"> Друзья пользователя:
            <br>
                {% for friend in userinfo.friends.all %}
                    {{ friend.username }}
                    <br>
                {% endfor %}

            </p>
            <p>
            Список постов пользователя:<br>
            {% for post in userinfo.user.post_author.all %}
            <a href="{% url 'webapp:post_detail' post.pk %}">{{ post.title }}</a>
                    <br>
            {% endfor %}
            </p>
            {% if request.user == userinfo.user %}
            <a href="{% url 'webapp:user_update' userinfo.pk %}">Редактировать</a>
            {% endif %}
        </div>



{% endblock %}

{% block scripts %}
<script>
        let button = document.getElementById('add-item-btn');
        let element = document.getElementById("phone");
        button.onclick = function() {
            element.innerText = "Телефон: {{ userinfo.phone }}";
        }
    </script>
{% endblock %}

social_network/webapp/templates/user_list.html
{% extends 'base.html' %}
{% block title %}{% endblock %}
{% block content %}
    {% for user in userinfo_list %}
        <div class="card mt-4 border">

                <a href="{% url 'webapp:user_detail' user.pk %}"><h3>{{ user.user }}</h3></a>

        </div>
    {% endfor %}
{% endblock %}

social_network/webapp/templates/user_update.html
{% extends 'base.html' %}
{% block title %}Изменить{% endblock %}
{% block content %}
    <h1>Редактирование</h1>
    <form action="{% url 'webapp:user_update' form.instance.pk %}" method="post" enctype="multipart/form-data">

<div class="form-group row">
{% csrf_token %}
    <label class="col-sm-2 col-form-label">Телефон:</label>
    <div class="col-sm-4">
        {{ form.phone }}
    </div>
</div>
<div class="form-group row">
    <label class="col-sm-2 col-form-label">Фото:</label>
    <div class="col-sm-4">
        {{ form.photo }}
    </div>
</div>
<div class="form-group row">
<label class="col-sm-2 col-form-label"></label>
    <div class="col-sm-4  mt-2">
      <button type="submit" class="btn btn-primary">Сохранить</button>
    </div>
</div>
    </form>
{% endblock %}